#include <fstream>


int main() {
  throw std::exception();
}  
      
  